### ISSUE TITLE
Sort recordings by date

### ISSUE THREAD

**Issue by maccabeelevine** [openlibraryenvironment/serverless-zoom-recordings#2]
Expected behavior: Recordings are sorted chronologically by date of recording.  (Either ascending or descending.)

Actual behavior: Recordings are not strictly chronological.  For example the current Technical Council page list (below) is ordered by month, but within that recordings appear randomly sorted:

* [23-Feb-2022 11:00 Eastern U.S. time](https://recordings.openlibraryfoundation.org/folio/tech-council/2022-02-23T11:00/)
* [9-Feb-2022 11:00 Eastern U.S. time](https://recordings.openlibraryfoundation.org/folio/tech-council/2022-02-09T11:00/)
* [2-Feb-2022 11:00 Eastern U.S. time](https://recordings.openlibraryfoundation.org/folio/tech-council/2022-02-02T11:00/)
* [16-Feb-2022 10:55 Eastern U.S. time](https://recordings.openlibraryfoundation.org/folio/tech-council/2022-02-16T10:55/)
* [2-Mar-2022 10:55 Eastern U.S. time](https://recordings.openlibraryfoundation.org/folio/tech-council/2022-03-02T10:55/)
* [16-Mar-2022 10:55 Eastern U.S. time](https://recordings.openlibraryfoundation.org/folio/tech-council/2022-03-16T10:55/)
* [9-Mar-2022 11:00 Eastern U.S. time](https://recordings.openlibraryfoundation.org/folio/tech-council/2022-03-09T11:00/)

**Comment by dltj** [comment]
Fixed with https://github.com/openlibraryenvironment/serverless-recordings-site/commit/b20300ef348492554f8f4a9f216ab0ed1fa867fd — thanks for your patience.
